[package]
name = "becquerelite"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irc = "0.15"
futures = "0.3"
failure = "0.1"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.19"
